FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

RUN export NODE_OPTIONS=--openssl-legacy-provider && yarn build && yarn install --production --ignore-scripts --prefer-offline
CMD ["npm","run","start"]